### ISSUE TITLE
'Do not damage tools' option missing

### ISSUE THREAD

**Issue by unidentifiablesolder23** [RakambdaOrg/FallingTree#230]
### Describe the bug

The 'Do not damage tools' option is missing from the config menu (using ModMenu found on the wiki).

### Minecraft version

1.17.1

### Fabric API version

0.41.0

### Mod version

2.14.2

**Comment by Rakambda** [comment]
There was two issues in one there, Split it up and opened #231 .

As for this issue, I think this has been removed long ago and never actually worked. But I can see to try to reimplement it.

**Comment by Rakambda** [comment]
I'm not really sure if I want to implement this actually.

This will cause quite some issues as the event that a block has been broken will have to be cancelled (a case of this is #11).
Plus this feels quite cheaty to me (even if it's your own decision in the end).

The best option there is probably to set your damage multiplicand to 0 so that each tree consumes 1 of durability which shouldn't be a big penalty.
