### ISSUE TITLE
Blacklist isn't work with Dynamic trees

### ISSUE THREAD

**Issue by ZEkA10000** [RakambdaOrg/FallingTree#269]
### Describe the bug

I set Dynamic trees into black list of mod because Falling Tree destroys tree without loot
Dynamic trees falls fine if Reverse Shift is OFF (There you can't instantly break vanilla trees)

![javaw_7EhTpXh4dK](https://user-images.githubusercontent.com/25690631/147590793-e1e86bbe-c1c8-4271-acb9-ab1706c3e727.png)

https://user-images.githubusercontent.com/25690631/147590780-febd381c-cf86-4168-9155-1ce771b921b7.mp4

### Minecraft version

1.16.5

### Forge version

36.2.22

### Mod version

2.11.5

**Comment by Rakambda** [comment]
The blacklist doesn't work because the IDs are incorrect (see red arrow in screenshot).

![image](https://user-images.githubusercontent.com/1688389/147592795-65a91b27-83aa-461d-a7fa-ad49ba6ba754.png)

If you want to have a cleaner config, you can directly blacklist the branches tag (blue arrow and second screenshot). That way all of them will be blacklisted and potential future trees will be handled too).

![image](https://user-images.githubusercontent.com/1688389/147593048-5faaa1b6-2662-4ff0-a323-bd95759e0781.png)
