### ISSUE TITLE
Mixed Logs Config

### ISSUE THREAD

**Issue by WenXin20** [RakambdaOrg/FallingTree#307]
### Describe the bug

The mixed logs config option doesn't seem to work. It is set to true but doesn't cut the tree if there is a stripped log above it.

### Minecraft version

1.18.1

### Forge version

39.0.65

### Mod version

3.2.0

**Comment by Rakambda** [comment]
I'm not sure that stripped log is considered a log by default.

Il investigate a bit later when I have time bit that is probably the issue. Adding stripped logs as logs may solve the issue.

**Comment by Rakambda** [comment]
Indeed stripped logs are not considered logs by default. You'll have to whitelist them to have them being handled by the mod.

Either you can list them one by one, like `minecraft;stripped_oak_log`, ...
Or you can add all logs with `#minecraft:logs`.

They are not whitelist by default as it's most likely that stripped appears in some building rather than in a tree.

**Comment by WenXin20** [comment]
Ah I hadn't thought of that since in 1.16 it had worked with stripped logs. Mainly since the Lord of the rings mod uses stripped logs in it's pine trees

**Comment by Rakambda** [comment]
Yeah that was changed with #148 which is for newer versions.

If that is mainly for that mod, probably can check if the mod author tags his logs with his own tag. Like that could just whitelist that tag to make things easier.

**Comment by WenXin20** [comment]
Yep, I'll do that once the mod updates to 1.18. Thanks for the help. :)

**Comment by WenXin20** [comment]
I also just realized that the Terralith mod/datapack makes a lot of its trees out of stripped logs
