### ISSUE TITLE
Radius leaf break

### ISSUE THREAD

**Issue by Yamza** [RakambdaOrg/FallingTree#5]
If trees are too close together the leaves won't break until you chop down all the trees. If possible, have some way of breaking the leaves in a radius around the logs removed.

**Comment by Rakambda** [comment]
As it is now it only breaks leaves that are going to despawn (like FastLeafDecay).

I added an option to define a radius in which the leaves will be forced destroyed. This will be applied from one of the top most log blocks and will destroy all leaves within it (including leaves that shouldn't despawn because another tree is too close, or because they've been placed by a player).

This will be in the next 1.15.2 release. I don't know if you're still on the 1.14 version.

**Comment by Yamza** [comment]
Been on 1.15.1, so all good. Thank you!
