### ISSUE TITLE
Timberjack-like felling animation

### ISSUE THREAD

**Issue by vico93** [RakambdaOrg/FallingTree#559]
### Describe the feature

Could something like this be implementable on your mod?
![Timberjack-Mod-1](https://github.com/Rakambda/FallingTree/assets/3485505/6df3a1bb-2033-4dd9-9556-f4947333fcce)

Its originally from [Timberjack](https://github.com/CovertJaguar/Timberjack), a fabulous mod by @CovertJaguar that unfortunately stopped being developed on 1.12.2.

**Comment by Rakambda** [comment]
I guess this is the same idea as #155.

For now I don't really have anything planned about it. The thing is falling tree is made to be "simple" and having the tree make a "mess" on the ground is kinda against it.
Though could be made so that the animation happens but blocks are still broken when landing.

May happen someday but can't say for sure.

**Comment by Rakambda** [comment]
I gave it a shot, you can try this build: https://github.com/Rakambda/FallingTree/actions/runs/5364781596

It probably won't get any better than this, just for "adding a cool style to it" sort of thing.

* FALL_ITEM is useable as it's same as INSTANTANEOUS but with the cool part.
* FALL_BLOCK may be annoying to use as it'll fall on the ground and then you'll have to break it again, plus the mod will fire again and do weird stuff.
