### ISSUE TITLE
Some config parameters doesn't work

### ISSUE THREAD

**Issue by Disketaa** [RakambdaOrg/FallingTree#573]
### Describe the bug

Greetings! I found that some of the config parameters doesn't change anything at all.
_Here's the config:_ 

```
{
  "trees": {
    "allowedLogs": [],
    "deniedLogs": [],
    "allowedLeaves": [],
    "allowedNonDecayLeaves": [],
    "deniedLeaves": [],
    "breakMode": "INSTANTANEOUS",
    "detectionMode": "ABOVE_CUT",
    "maxScanSize": 500,
    "maxSize": 50,
    "maxSizeAction": "CUT",
    "breakOrder": "CLOSEST_FIRST",
    "minimumLeavesAroundRequired": 1,
    "includePersistentLeavesInRequiredCount": true,
    "treeBreaking": true,
    "leavesBreaking": true,
    "leavesBreakingForceRadius": 0,
    "allowMixedLogs": false,
    "breakNetherTreeWarts": true,
    "instantlyBreakWarts": false,
    "breakMangroveRoots": true,
    "searchAreaRadius": -1,
    "allowedAdjacentBlocks": [],
    "adjacentStopMode": "STOP_ALL"
  },
  "tools": {
    "allowed": [],
    "denied": [],
    "preserve": false,
    "ignoreTools": false,
    "damageMultiplicand": 1.25,
    "damageRounding": "ROUND_DOWN",
    "speedMultiplicand": 0.75,
    "forceToolUsage": false
  },
  "player": {
    "allowedTags": []
  },
  "enchantment": {
    "registerEnchant": false,
    "registerSpecificEnchant": false,
    "hideEnchant": false
  },
  "sneakMode": "IGNORE",
  "breakInCreative": false,
  "lootInCreative": true,
  "notificationMode": "NONE"
}
```

1. Tools are getting saved on 1 durability point even if the value sets to false.
![13](https://github.com/Rakambda/FallingTree/assets/76956762/36234107-9073-438f-b209-184b30d88432)

2. Mangrove roots doesn't destroys
![14](https://github.com/Rakambda/FallingTree/assets/76956762/de4b3b19-c5f1-4472-bbc8-e5ce48ab030d)

3. Break nether leaves with one hit doesn't affect anything (or I don't get it) plus some of warts keep floating in the air
![15](https://github.com/Rakambda/FallingTree/assets/76956762/5091cfcf-c23b-4680-a469-55db7ccc58d9)

Here's my modlist, I didn't check the issue with blank MC and only Falling Tree mod cause I'm not sure that'll change anything
![image](https://github.com/Rakambda/FallingTree/assets/76956762/28412057-39f9-4baf-b7c3-7af0a83c73fa)

### Minecraft version

1.20

### Fabric API version

0.85.0

### Mod version

4.2.1

**Comment by Rakambda** [comment]
1. This is actually the case because of the damage multiplicand.
From my testing, I have an axe with 4 burability and the 1.25 multiplicand. It means that I'm allowed to break 4/1.25 = 3.2 blocks. So it'll break max 3 blocks.
This will as a result leave a durability of 1. This is this way because otherwise you'd break more blocks than the multiplied durability allows.
2. You have set Trees > Detection Mode = above cut. As the roots are below the log that is cut, it isn't taken into account.
3. The "break warts" will break the warts (leaves) as you saw. Though you have a max tree size of 50 defined so it'll often be more blocks than this and therefore cut only parts of the tree. The "with one hit" variant is only useful with the shift down method. I can probably clarify that in a future release as it's not too urgent.

**Comment by Disketaa** [comment]
Thanks for the explanation <3
