### ISSUE TITLE
Break blocks from Regions Unexplored (apple leaves block etc)

### ISSUE THREAD

**Issue by lospejos** [RakambdaOrg/FallingTree#625]
### Describe the feature

When using together `Falling Tree` mod together with `Regions Unexplored`, blocks from `Regions Unexplored` (apple leaves) does not break when the rest of the tree was successfully broken.

Please make mods compatible. Thanks.

**Comment by Rakambda** [comment]
FallingTree is only forcing random ticking on leaves. In the case of "normal" leaves it works as it check for a log nearby, and as the log is gone, it'll destroy itself.
I don't know how `Regions Unexplored` works, but glancing quickly [at the code](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/main/src/main/java/net/regions_unexplored/world/level/block/leaves/AppleLeavesBlock.java#L43-L60), it seems the "decay" of the leaves is based onto something else (called "age"). So the random ticking doesn't have an effect on it as the log isn't a condition for it to break.
I guess that if without falling tree you break the trunk, it'll wait for the leaves to be fully aged too.

If you really want to destroy them, you can set a force breaking leaves radius within the FallingTree config (tree section).

Other than this I see it more as an intended behavior ffrom the `Regions Unexplored` mod author => trunk being removed doesn't mean leaves should disappear.

**Comment by Rakambda** [comment]
Ok my bad, seems like https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/main/src/main/java/net/regions_unexplored/world/level/block/leaves/AppleLeavesBlock.java#L44 is actually checking for distance, i'll investigate more.

**Comment by Rakambda** [comment]
Ok so analyzing this a bit more leads to : 

* If you have leaves that are not aged completly (age < 4), then i'd guess fallingtree would break the leaves properly, right ?
* Otherwise, when age = 4, this doesn't happen because the leaves explicitely [says they cannot be random ticked](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/main/src/main/java/net/regions_unexplored/world/level/block/leaves/AppleLeavesBlock.java#L38-L40C3) and fallingtree honors what the block says.

To be honest I don't know what sould be the position on this. I can understand why this was made : so that when a leaf is fully aged, minecraft doesn't waste time to make it grow more. However this also inhibits the leaf from decaying when the log is gone. It's like the block has become a resource and needs to be harvested.

I guess i'd still see it as a bug/wanted behavior on the `Regions Unexplored` side of things. In a perfect world the `isRandomlyTicking` method should probably return something like `return state.getValue(AGE) < 4 || super.isRandomlyTicking(state)` so that it also takes into account the vanilla behavior of leaves.
As it is, even without fallingtree, fully ages leaves would never decay, so it is a "behavior" fallingtree cannot accelerate.

**Comment by lospejos** [comment]
@Rakambda Thanks for your time spent and effort, appreciate that!
