### ISSUE TITLE
log vs wood

### ISSUE THREAD

**Issue by FudgeDumbo** [RakambdaOrg/FallingTree#632]
### Describe the feature

is it possible to include wood blocks as part of the tree as well? and maybe the mangrove root block too
it seems that the mod does not recognize the wood blocks as part of the tree if logs and woods are mixed in.

thank you~

**Comment by Rakambda** [comment]
I'm not sure to get it all.
By woods you mean the result of putting logs in the crafting bench?

If so, this is intentional, a tree isn't made of planks but of logs. If you have cases where this happens, you can add those blocks in the config as being logs.
But also that means you can possibly chop down a house made of it.

"Mixed", for that there's an option to allow detection of mixed logs (assuming FallingTree knows that those "woods" are logs).

"Mangrove roots", if I remember well there's an option to enable breaking those along with the trunk.

**Comment by FudgeDumbo** [comment]
sorry if you were confused heh.
if you put 4 logs you get woods, not planks.... woods are the blocks that has all 6 sides covered with bark/outer layer
i just happend to have a trees from a mod that spawns with logs and woods.

**Comment by Rakambda** [comment]
I consider wood as being a building block (it doesn't appear naturally in the wild in vanilla). You'll therefore have to add these blocks in the config under `Trees > Allowed logs blocks`.

Either the author provided a tag for those bloks and you can use something like `#minecraft:woods`, ortherwise you'll have to add them 1 by 1 with something like `minecraft:weed_block`.

**Comment by FudgeDumbo** [comment]
I see, I will try the tag system or the config :)

Thank you~
