### ISSUE TITLE
Trees only slightly break at times when axe used breaks.

### ISSUE THREAD

**Issue by R3STE4SY** [RakambdaOrg/FallingTree#67]
**Describe the bug**
When breaking a tree, if the axe you are using breaks, sometimes it will only partially destroy the tree.

**Infos:**
 - Minecraft verson: 1.16.5
 - Mod loader: Fabric

**Comment by Rakambda** [comment]
This is the desired effect. If there isn't enough durability on the tool, it'll only break what it can and no more.

What you can do is to set `Tools > damage multiplicand` to `0`. It'll basically use `1` of durability for every tree cut (instead of the amount of logs). Though it is a bit more "cheaty" as you use way less durability.

About the issue itself I'm not sure I want to change it. To me this allows to add some sort of drawback to the mod. As it gives advantages by cutting it in one go it's your responsibility to have what is needed to cut it or you took may break and/or get a floating tree.

What I can do maybe if it seem interesting to you is to add a configuration that would dissalow the cutting in that case. Basically if you don't have enough durability to break everything then you get a message in the chat and nothing happens.
