### ISSUE TITLE
Leaves backlist/whitelist isn't saved

### ISSUE THREAD

**Issue by FrederikT** [RakambdaOrg/FallingTree#76]
Whitelisted Leaves does not work. The GUI option adds Blocks to logs_whitelisted in the config file. manually adding leaves_whitelisted in config file doesn't work either. After starting minecraft leaves_whitelisted is removed.
logs_whitelisted  works fine. 
(I have the mod "Oh The Biomes You'll Go" installed. The embur "tree" from a nether biome has "byg:embur_gel_block" and "minecraft:shroomlight" as leaves. they will not be cut while the logs are cut. )

**Comment by Rakambda** [comment]
>  and "minecraft:shroomlight" as leaves

Just as info: this should already be handled by default if you have the `breakNetherTreeWarts` configuration activated.

> The embur "tree" from a nether biome has "byg:embur_gel_block"

Does this block decay by default?
Because if it doesn't then it's normal that it isn't cut. FallingTree just speeds up the decay.

Concerning that point I plan to add a configuration to add other "type" of leaves, like warts, that requires to be mined. But I don't know when it'll be implemented.

> After starting minecraft leaves_whitelisted is removed.

That's strange. Do you have an example of the value in the config when this happens?

**Comment by Rakambda** [comment]
> After starting minecraft leaves_whitelisted is removed.

Ok that one I found it, will be fixed
