### ISSUE TITLE
Speed multiplicand doesn't work with mod Project MMO.

### ISSUE THREAD

**Issue by Mihail001** [RakambdaOrg/FallingTree#80]
**Describe the bug**
Speed multiplicand doesn't work with mod Project MMO installed.
If I want to cut all tree I cut it down in just 3 seconds. And I change the speed multiplicand to: 0.4

**To Reproduce**
1. Install: Project_MMO-1.16.4-3.49.2 and FallingTree-Forge-1.16.5-2.11.0.
2. Join the world.
3. Cut the tree with any axe.
4.  

https://user-images.githubusercontent.com/74407310/112761074-10bba780-9002-11eb-814a-a92cf6ac57c7.mp4

**Infos:**
 - Minecraft version: [1.16.5]
 - Mod loader: [Forge-36.1.2]
 - Mod version: [FallingTree-Forge-1.16.5-2.11.0]

**Comment by Rakambda** [comment]
Honestly I'm not really sure if I can do anything about it.

What happens:
* FallingTree will handle the breakSpeed event as it have a priority `NORMAL` (ref: https://github.com/RakSrinaNa/FallingTree/blob/1.16.5-forge/src/main/java/fr/raksrinana/fallingtree/ForgeEventSubscriber.java#L45-L62)
  * In your case this will set the break speed as being `0.4 * <time to break one log> * log_count`
* Then Project MMO will handle the event on its side as it have a priority `LOWEST` (will always be executed last) (ref: https://github.com/Harmonised7/project_mmo/blob/master/src/main/java/harmonised/pmmo/events/EventHandler.java#L109-L113) 
  * This will calculate the breaking speed based on your tool xp? (idk how MMO works i'm just guessing). But by doing that it'll overwrite what FallingTree defined.
 

As MMO will always be executed last due to its priority I see only 2 ways this could be fixed:
* Project MMO adds an option to activate/deactivate the speed change (so that it lets FallingTree decide the new speed)
* Instead of calculating the speed from `originalSpeed`, it calculates it from `newSpeed`. This would make it so that if any other mod first modified the speed, it'll make its changes based on that new speed. So for example falling tree applies the 0.4 speed multiplicand, and then MMO may adapt that speed based on your tool xp. (https://github.com/Harmonised7/project_mmo/blob/master/src/main/java/harmonised/pmmo/events/BreakSpeedHandler.java#L64-L101)

If people see any other options I'm open to hearing them.

To be coherent I'll do the same in FallingTree, use `originalSpeed` as a source of "truth" so that it takes into account other mods modifications. But that will only apply only to mods that changes speed BEFORE it. So in the case of project MMO I can't do much more, it'll have the last word.

**Comment by Rakambda** [comment]
The commit above is now released. It won't change anything to the problem.

As said in the comment above, it needs action from project MMO too. And as it seems like nothing changed, i'll close it for now.
