### ISSUE TITLE
Enchant varient

### ISSUE THREAD

**Issue by Zidiath** [RakambdaOrg/FallingTree#99]
Enchanting variant in the config to lock the FallingTree event behind a enchantment

**Comment by Rakambda** [comment]
I don't really know if I'll do it for now. But it's a good suggestion.

Pros:
* Easier than a whitelist/blacklist
* Can be enable per item instead of per "item type"

Cons:
* Would need to have the mod on both server and client, couldn't have it only server side

I don't know if it'd be better to have 2 separate mods, one working with a whitelist/blacklist, and the other with the enchant. To me it'd make things a bit complicated if they're both together.

**Comment by Rakambda** [comment]
As an update, I think I'll go on and implement it, but not as a variant. It'll simply be part of the mod itself.

What I think : 

- Have an option to require the enchant or not : 
  - If yes (default) then you'd need to have the enchant for the chopping to be applied
  - If no then it stays the same as now
- The whitelist/blacklist of tools still is present but now becomes a more generic info : 
  - If the enchant is activated then you need a tool that is whitelisted but not blacklisted. 
    i.e if you have the enchant on a blacklisted axe, it won't work
    i.e if you have the enchant on a whitelisted furnace, it'll work.
  - If the enchant is deactivated, it's like before
- For server players, the mod will be needed on both client and server, but well, I think that people playing on servers won't see that much difference having one more mod on their side 😆
